#!/bin/bash
mkdir .logs
wget https://raw.githubusercontent.com/jaws316/Raspberry_Pi_Server/main/bashrc-add
cat bashrc-add >> .bashrc
echo "Bashrc Done"
echo ""
mkdir .bin
cd .bin
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/aip
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/lip
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/wip
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/update
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/check-my-net
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/HTTPServer
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/sr
wget https://raw.githubusercontent.com/jaws316/Bash_Scripts/main/sh
chmod 777 *
cd
echo "Bin Done"
echo ""
dpkg -l | grep -qw tmux || sudo apt install -yyq tmux
dpkg -l | grep -qw nano || sudo apt install -yyq nano
dpkg -l | grep -qw ncdu || sudo apt install -yyq ncdu
dpkg -l | grep -qw htop || sudo apt install -yyq htop
dpkg -l | grep -qw sshfs || sudo apt install -yyq sshfs
dpkg -l | grep -qw speedtest-cli || sudo apt install -yyq speedtest-cli
dpkg -l | grep -qw neofetch || sudo apt install -yyq neofetch
dpkg -l | grep -qw dnsutils || sudo apt install -yyq dnsutils
dpkg -l | grep -qw plocate || sudo apt install -yyq plocate
dpkg -l | grep -qw net-tools || sudo apt install -yyq net-tools
sudo updatedb
echo "Programs Insealled"
echo ""
wget https://raw.githubusercontent.com/jaws316/Raspberry_Pi_Server/main/nf
echo "NeoFetch Done"
echo ""
wget https://raw.githubusercontent.com/jaws316/Raspberry_Pi_Server/main/zerotier
bash zerotier
echo "zerotier Done"
rm rpiserver-setup
rm bashrc-add
rm zerotier
echo "All Done"
echo ""
